"""Reporting data contracts and helpers."""

from orchestrator.reporting.report_data import (
    KNOWN_ITERATION_STATUSES,
    REPORT_GENERATOR,
    REPORT_PROFILE_BASIC_SINGLE_EXPERIMENT,
    REPORT_SCHEMA_VERSION,
    ExperimentReportInfo,
    ReportArtifactMap,
    ReportBaselineMetrics,
    ReportBenchmarkConfig,
    ReportClosedLoopSelection,
    ReportData,
    ReportDiffStats,
    ReportExperimentMetadata,
    ReportExperimentConfigDetails,
    ReportFinalBestCandidate,
    ReportFinalSelection,
    ReportFinalResult,
    ReportIterationSummary,
    ReportLlmInfo,
    ReportLlmUsage,
    ReportLlmUsageSummary,
    ReportMetadata,
    ReportOutcomeReason,
    ReportPhaseTimings,
    ReportReasonCodeCount,
    ReportReasonSummaryItem,
    ReportReportingStatus,
    ReportSelectionPolicy,
    ReportStatusCounts,
    default_status_counts,
    make_empty_report_data,
    to_report_dict,
    write_report_data,
)
from orchestrator.reporting.report_data_collector import (
    collect_and_write_report_data,
    collect_report_data,
)
from orchestrator.reporting.figure_builder import build_report_figures
from orchestrator.reporting.generate_report import (
    generate_basic_html_report,
    generate_basic_report,
    refresh_report_artifact_map,
)
from orchestrator.reporting.html_renderer import render_report_html
from orchestrator.reporting.pdf_exporter import PdfExportError, export_pdf_from_html
from orchestrator.reporting.report_inspector import inspect_report

__all__ = [
    "KNOWN_ITERATION_STATUSES",
    "REPORT_GENERATOR",
    "REPORT_PROFILE_BASIC_SINGLE_EXPERIMENT",
    "REPORT_SCHEMA_VERSION",
    "ExperimentReportInfo",
    "ReportArtifactMap",
    "ReportBaselineMetrics",
    "ReportBenchmarkConfig",
    "ReportClosedLoopSelection",
    "ReportData",
    "ReportDiffStats",
    "ReportExperimentMetadata",
    "ReportExperimentConfigDetails",
    "ReportFinalBestCandidate",
    "ReportFinalSelection",
    "ReportFinalResult",
    "ReportIterationSummary",
    "ReportLlmInfo",
    "ReportLlmUsage",
    "ReportLlmUsageSummary",
    "ReportMetadata",
    "ReportOutcomeReason",
    "ReportPhaseTimings",
    "ReportReasonCodeCount",
    "ReportReportingStatus",
    "ReportSelectionPolicy",
    "ReportStatusCounts",
    "PdfExportError",
    "ReportReasonSummaryItem",
    "build_report_figures",
    "collect_and_write_report_data",
    "collect_report_data",
    "default_status_counts",
    "generate_basic_html_report",
    "generate_basic_report",
    "refresh_report_artifact_map",
    "inspect_report",
    "make_empty_report_data",
    "render_report_html",
    "export_pdf_from_html",
    "to_report_dict",
    "write_report_data",
]
